CREATE TABLE URL_DETAILS
(
    ID           bigint(20) NOT NULL AUTO_INCREMENT,
    ALIAS_URL    VARCHAR(512) NOT NULL UNIQUE,
    ORIGINAL_URL TEXT  NOT NULL,
    REDIRECT     BOOLEAN NOT NULL DEFAULT FALSE,
    MODIFIED_ON  bigint(20),
    PRIMARY KEY(ID)
)